paths:
  output_dir: outputs
  train_data: /home/user933/Desktop/asds/LLM-Detect-AI-Generated-Text/data/train_with_spacy_features.csv
  test_data: /home/user933/Desktop/asds/LLM-Detect-AI-Generated-Text/data/manual_test_data.csv